/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

/**
 *
 * @author ABC
 */
public class AfterLogin extends javax.swing.JFrame {

    /**
     * Creates new form AfterLogin
     */
    myrequests req = new myrequests();
    Home home = new Home();
    postbloodrequirement pbr = new postbloodrequirement();
    notifications noti = new notifications();
    volunteerforblood volu=new volunteerforblood();
    checkmyrequest myreq=new checkmyrequest();
    ChangeCredentials cngCred = new ChangeCredentials();
    deleteBloodRequirements dbr = new deleteBloodRequirements();

    public AfterLogin() {
        initComponents();
        nameLabel.setText("Name : "+UserDetails.name);
        bgLabel.setText("Blood Group : "+UserDetails.bloodGroup);
        cnoLabel.setText("Contact No : "+UserDetails.mobileNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        signOutBtn = new javax.swing.JButton();
        postRequirementBtn = new javax.swing.JButton();
        volunteerBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        myRequestBtn = new javax.swing.JButton();
        checkMyRequestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();
        cnoLabel = new javax.swing.JLabel();
        changeCredentialsBtn = new javax.swing.JButton();
        deleteBloodRequirementsBtn = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blood Bank");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);

        signOutBtn.setBackground(new java.awt.Color(255, 255, 255));
        signOutBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        signOutBtn.setText("Sign out");
        signOutBtn.setBorder(null);
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });

        postRequirementBtn.setBackground(new java.awt.Color(255, 255, 255));
        postRequirementBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        postRequirementBtn.setText("Post Blood Requirement");
        postRequirementBtn.setBorder(null);
        postRequirementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postRequirementBtnActionPerformed(evt);
            }
        });

        volunteerBtn.setBackground(new java.awt.Color(255, 255, 255));
        volunteerBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        volunteerBtn.setText("Donate Blood");
        volunteerBtn.setBorder(null);
        volunteerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(255, 255, 255));
        homeBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(null);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        myRequestBtn.setBackground(new java.awt.Color(255, 255, 255));
        myRequestBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        myRequestBtn.setText("My Requested Posts");
        myRequestBtn.setBorder(null);
        myRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myRequestBtnActionPerformed(evt);
            }
        });

        checkMyRequestBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkMyRequestBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        checkMyRequestBtn.setText("Check My Requested Posts");
        checkMyRequestBtn.setBorder(null);
        checkMyRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMyRequestBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_login-user-icon.png"))); // NOI18N

        nameLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        nameLabel.setText("Name : ");

        bgLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        bgLabel.setText("Blood Group : ");

        cnoLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        cnoLabel.setText("Contact No : ");

        changeCredentialsBtn.setBackground(new java.awt.Color(255, 255, 255));
        changeCredentialsBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        changeCredentialsBtn.setText("Change Credentials");
        changeCredentialsBtn.setBorder(null);
        changeCredentialsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCredentialsBtnActionPerformed(evt);
            }
        });

        deleteBloodRequirementsBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBloodRequirementsBtn.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        deleteBloodRequirementsBtn.setText("Delete Blood Requirement");
        deleteBloodRequirementsBtn.setBorder(null);
        deleteBloodRequirementsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBloodRequirementsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(signOutBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volunteerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(postRequirementBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                        .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkMyRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(changeCredentialsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(bgLabel)
                            .addComponent(cnoLabel))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(deleteBloodRequirementsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnoLabel)))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(postRequirementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volunteerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkMyRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeCredentialsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBloodRequirementsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkMyRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMyRequestBtnActionPerformed
        checkMyRequestBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        deleteBloodRequirementsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);
       
        volunteerBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        desktop.add(myreq);
        home.dispose();
        noti.dispose();
        dbr.dispose();
        req.dispose();
        volu.dispose();
        pbr.dispose();
        cngCred.dispose();
        myreq.setVisible(true);
        
       
    }//GEN-LAST:event_checkMyRequestBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        homeBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        deleteBloodRequirementsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);
       
        checkMyRequestBtn.setEnabled(true);
        volunteerBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        desktop.add(home);
        pbr.dispose();
        req.dispose();
        noti.dispose();
        dbr.dispose();
        volu.dispose();
        myreq.dispose();
        cngCred.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void postRequirementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postRequirementBtnActionPerformed
        postRequirementBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        deleteBloodRequirementsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);
    
        checkMyRequestBtn.setEnabled(true);
        volunteerBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        desktop.add(pbr);
        home.dispose();
        noti.dispose();
        req.dispose();
        dbr.dispose();
        volu.dispose();
        myreq.dispose();
        cngCred.dispose();
        pbr.setVisible(true);
    }//GEN-LAST:event_postRequirementBtnActionPerformed

    private void volunteerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerBtnActionPerformed
        volunteerBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        deleteBloodRequirementsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);

        checkMyRequestBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        desktop.add(volu);
        myreq.dispose();
        home.dispose();
        noti.dispose();
        req.dispose();
        pbr.dispose();
        dbr.dispose();
        cngCred.dispose();
        volu.setVisible(true);
    }//GEN-LAST:event_volunteerBtnActionPerformed

    private void myRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRequestBtnActionPerformed
        myRequestBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        deleteBloodRequirementsBtn.setEnabled(true);
        checkMyRequestBtn.setEnabled(true);
       
        volunteerBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        
        desktop.add(req);
        home.dispose();
        pbr.dispose();
        noti.dispose();
        myreq.dispose();
        volu.dispose();
        cngCred.dispose();
        dbr.dispose();
        req.setVisible(true);
    }//GEN-LAST:event_myRequestBtnActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        dispose();
        LoginPage l = new LoginPage();
        l.setLocationRelativeTo(null);
        l.setVisible(true);
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void changeCredentialsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCredentialsBtnActionPerformed
        changeCredentialsBtn.setEnabled(false);
        deleteBloodRequirementsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);

        checkMyRequestBtn.setEnabled(true);
        volunteerBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        
        desktop.add(cngCred);
        home.dispose();
        pbr.dispose();
        noti.dispose();
        myreq.dispose();
        volu.dispose();
        req.dispose();
        dbr.dispose();
        cngCred.setVisible(true);
    }//GEN-LAST:event_changeCredentialsBtnActionPerformed

    private void deleteBloodRequirementsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBloodRequirementsBtnActionPerformed
        deleteBloodRequirementsBtn.setEnabled(false);
        changeCredentialsBtn.setEnabled(true);
        myRequestBtn.setEnabled(true);
  
        checkMyRequestBtn.setEnabled(true);
        volunteerBtn.setEnabled(true);
        postRequirementBtn.setEnabled(true);
        homeBtn.setEnabled(true);
        desktop.add(dbr);
        home.dispose();
        noti.dispose();
        req.dispose();
        volu.dispose();
        pbr.dispose();
        cngCred.dispose();
        dbr.setVisible(true);
    }//GEN-LAST:event_deleteBloodRequirementsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton changeCredentialsBtn;
    private javax.swing.JButton checkMyRequestBtn;
    private javax.swing.JLabel cnoLabel;
    private javax.swing.JButton deleteBloodRequirementsBtn;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton myRequestBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton postRequirementBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JButton volunteerBtn;
    // End of variables declaration//GEN-END:variables
}
