/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ABC
 */
public class deleteBloodRequirements extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    String requirementChecker;
    int check=0;
    
    public deleteBloodRequirements() {
        initComponents();
        /* REMOVE THE DROP DOWN BUTTON FROM FRAME */
        Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        pane.remove(0);
        pane.getComponent(0).setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(539, 540));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Enter ID");

        deleteBtn.setText("Delete Requirement");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        errorMsg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        errorMsg.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(id)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String id1 = id.getText();
        
        if (id1.length() == 0) {
            errorMsg.setForeground(Color.red);
            errorMsg.setText("Please enter an ID");
        }
        
        else {
            
            DB_Connection ob = new DB_Connection();
            Connection conn = ob.get_connection();
            PreparedStatement ps=null;
            
            try {
                
                    String query="select req_id from BloodRequirement where u_id="+UserDetails.id;
                    PreparedStatement p=conn.prepareStatement(query);
                    ResultSet rs=p.executeQuery();
                    while(rs.next()){
                        requirementChecker=""+ rs.getString("req_id");
                        if(requirementChecker.equals(id1)){
                            check=-1;
                            break;
                        }
                    }
                    
                    if (check==-1) {
                        String sql="Delete from BloodRequirement WHERE req_id="+id1+" AND u_id="+UserDetails.id;
                        PreparedStatement preparedStatement = conn.prepareStatement(sql);
                        preparedStatement.executeUpdate();
                        errorMsg.setForeground(Color.green);
                        errorMsg.setText("Your Blood Requirement has been deleted");
                    }
                    
                    else {
                        errorMsg.setForeground(Color.red);
                        errorMsg.setText("You don't have any requirement with ID : "+id1);
                    }
                
            } catch (Exception e) {
                
            }
            
        }
        
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
