/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ABC
 */
public class myrequests extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    public myrequests() {
        initComponents();
        /* REMOVE THE DROP DOWN BUTTON FROM FRAME */
        Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        pane.remove(0);
        pane.getComponent(0).setVisible(false);
        requestList();
    
    }
    
    
     public void requestList() {
        DefaultListModel<myRequestObjects> dlm = new DefaultListModel<myRequestObjects>();
        
        int a=0;
        
        int emptycount=0;
        
        DB_Connection ob = new DB_Connection();
        Connection conn = ob.get_connection();
        PreparedStatement ps = null;
        
        try {
            
            String qry = "SELECT count(*) From BloodRequirement";
            ps=conn.prepareStatement(qry);
            ResultSet rs=ps.executeQuery();
            while(rs.next()) {
                emptycount=rs.getInt("count(*)");
            }
            
            if (emptycount==0) {
                dlm.addElement(new myRequestObjects("You have no Blood Requirements yet."));
                jList1.setModel(dlm);
                jList1.setCellRenderer(new myRequestEmptyTableModel());
            }
            
            else if (emptycount!=0) {
                
                String query="select * from BloodRequirement where u_id="+UserDetails.id;
                ps=conn.prepareStatement(query);
                ResultSet rs1=ps.executeQuery();
                
                String id,name,bg,cno,loc,urgency,date;
                    
                while (rs1.next()) {
                    if (rs1.getInt("u_id") == Integer.parseInt(UserDetails.id)) {
                        a=1;
                        id = rs1.getString("req_id");
                        name = rs1.getString("p_name");
                        bg = rs1.getString("p_bloodgroup");
                        cno = rs1.getString("p_contactno");
                        loc = rs1.getString("p_location");
                        urgency = rs1.getString("p_urgency");
                        date = rs1.getString("p_date");
                
                        dlm.addElement(new myRequestObjects("ID : "+id, "Name : "+name, "Blood Group : "+bg,"Contact No : "+cno,"Location : "+loc,"Urgency : "+urgency,"Date : "+date));
                        jList1.setModel(dlm);
                        jList1.setCellRenderer(new myRequstsModel());
                    }
                     
                }
                
                if (a==0) {
                    dlm.addElement(new myRequestObjects("You have no Blood Requirements yet."));
                    jList1.setModel(dlm);
                    jList1.setCellRenderer(new myRequestEmptyTableModel());
                }
                
            }
            conn.close();
            
        } catch (Exception e) {
            
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        refreshBtn = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(539, 540));

        jScrollPane1.setViewportView(jList1);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        requestList();
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<myRequestObjects> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
