/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

/**
 *
 * @author ABC
 */
public class myRequstsModel extends javax.swing.JPanel implements ListCellRenderer<myRequestObjects> {

    /**
     * Creates new form listModel
     */
    public myRequstsModel() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rbloodgroup = new javax.swing.JLabel();
        rcontactno = new javax.swing.JLabel();
        rlocation = new javax.swing.JLabel();
        rname = new javax.swing.JLabel();
        rid = new javax.swing.JLabel();
        rurgency = new javax.swing.JLabel();
        rdate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        rbloodgroup.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rbloodgroup.setText("Blood Group : ");

        rcontactno.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rcontactno.setText("Contact No : ");

        rlocation.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rlocation.setText("Location : ");

        rname.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rname.setText("Name : ");

        rid.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rid.setText("ID :");

        rurgency.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rurgency.setText("Urgency : ");

        rdate.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        rdate.setText("Date : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbloodgroup)
                    .addComponent(rname)
                    .addComponent(rid)
                    .addComponent(rurgency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rlocation)
                    .addComponent(rcontactno)
                    .addComponent(rdate))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(rid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rname)
                    .addComponent(rcontactno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbloodgroup)
                    .addComponent(rlocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rurgency)
                    .addComponent(rdate))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rbloodgroup;
    private javax.swing.JLabel rcontactno;
    private javax.swing.JLabel rdate;
    private javax.swing.JLabel rid;
    private javax.swing.JLabel rlocation;
    private javax.swing.JLabel rname;
    private javax.swing.JLabel rurgency;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends myRequestObjects> list, myRequestObjects value, int index, boolean isSelected, boolean cellHasFocus) {
       
        this.rid.setText(value.rid);
        this.rname.setText(value.rname);
        this.rbloodgroup.setText(value.rbloodgroup);
        this.rcontactno.setText(value.rContactno);
        this.rlocation.setText(value.rLocation);
        this.rdate.setText(value.rDate);
        this.rurgency.setText(value.rUrgency);
        
        return this;
    
    }

   
}
