/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ABC
 */
public class volunteerforblood extends javax.swing.JInternalFrame {

    /**
     * Creates new form Home
     */
    String bloodGroupChecker;
    
    public volunteerforblood() {
        initComponents();
        /* REMOVE THE DROP DOWN BUTTON FROM FRAME */
        Container pane = ((BasicInternalFrameUI) this.getUI()).getNorthPane();
        pane.remove(0);
        pane.getComponent(0).setVisible(false);
        
        volbtn.setEnabled(false);
        comentbtn.setEnabled(false);
        voleunits.setEnabled(false);
        voletime.setEnabled(false);
        volcomment.setEnabled(false);
    }
    
    DB_Connection ob = new DB_Connection();
    Connection conn =ob.get_connection();
    PreparedStatement ps=null;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        volok = new javax.swing.JButton();
        u_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        voleunits = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        volbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volcomment = new javax.swing.JTextArea();
        comentbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        voletime = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        volblood = new javax.swing.JLabel();
        volcontactno = new javax.swing.JLabel();
        vollocation = new javax.swing.JLabel();
        volname = new javax.swing.JLabel();
        volurgency = new javax.swing.JLabel();
        voldate = new javax.swing.JLabel();
        errormsg = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(539, 540));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("Enter ID");

        volok.setText("OK");
        volok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volokActionPerformed(evt);
            }
        });

        u_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_idActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setText("Unit(s)");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel3.setText("Volunteer");

        volbtn.setText("Volunteer");
        volbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel4.setText("Comment");

        volcomment.setColumns(20);
        volcomment.setRows(5);
        jScrollPane1.setViewportView(volcomment);

        comentbtn.setText("Comment");
        comentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comentbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel5.setText("Time");

        volblood.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        volblood.setText("Blood Group : ");

        volcontactno.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        volcontactno.setText("Contact No : ");

        vollocation.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        vollocation.setText("Location : ");

        volname.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        volname.setText("Name : ");

        volurgency.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        volurgency.setText("Urgency : ");

        voldate.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        voldate.setText("Date : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volblood)
                    .addComponent(volname)
                    .addComponent(volurgency))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vollocation)
                    .addComponent(volcontactno)
                    .addComponent(voldate))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volname)
                    .addComponent(volcontactno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volblood)
                    .addComponent(vollocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volurgency)
                    .addComponent(voldate))
                .addGap(9, 9, 9))
        );

        errormsg.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        errormsg.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(volok))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(voleunits, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(volbtn)
                                            .addComponent(voletime))))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comentbtn)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(errormsg, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(134, 134, 134))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(volok)
                    .addComponent(u_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comentbtn)
                            .addComponent(volbtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(voleunits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(voletime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(errormsg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volokActionPerformed
        int emptycount=0;
                
               
                
                String gid=u_id.getText();
                int vvid=Integer.parseInt(gid);
                
               
                int a=0;
                
                try{
                    
                    String qry="Select count(*) from Users";
                    ps=conn.prepareStatement(qry);
                    ResultSet rs=ps.executeQuery();
                    while(rs.next()){
                        
                        emptycount=rs.getInt("count(*)");
                        
                    }
                    
                    if(emptycount==0){
                        JOptionPane.showMessageDialog(null,"Account does't exists");
                    }
                    
                    
                    else{
                        
                         String query="Select * From BloodRequirement where req_id= "+vvid;
                         ps=conn.prepareStatement(query);
                         rs=ps.executeQuery();
                        ///
                        
                        
                        
                        
                        
                        while(rs.next()){
                            
                            
                        if(rs.getInt("req_id")==vvid){ 
                            bloodGroupChecker=rs.getString("p_bloodgroup");
                            a=1;
                            volname.setText("Name : "+rs.getString("p_name"));
                            volblood.setText("Blood Group : "+rs.getString("p_bloodgroup"));
                            volurgency.setText("Urgency : "+rs.getString("p_urgency"));
                            volcontactno.setText("Contact No : "+rs.getString("p_contactno"));
                            vollocation.setText("Location : "+rs.getString("p_location"));
                            voldate.setText("Date : "+rs.getString("p_date"));
                            errormsg.setText("");
                            
                            volbtn.setEnabled(true);
                            comentbtn.setEnabled(true);
                            voleunits.setEnabled(true);
                            voletime.setEnabled(true);
                            volcomment.setEnabled(true);
                        
                            
                            
                            
                        }
                        
                        else if (rs.getInt("req_id")!=vvid) {
                            a=0;
                        }
                             
                        }
                        
                        
                        if (a==0) {
                           errormsg.setForeground(Color.red);
                           errormsg.setText("ID doesn't exist");
                           volbtn.setEnabled(false);
                           comentbtn.setEnabled(false);
                           voleunits.setEnabled(false);
                           voletime.setEnabled(false);
                           volcomment.setEnabled(false);
                           volname.setText("Name : ");
                           volblood.setText("Blood Group : ");
                           volurgency.setText("Urgency : ");
                           volcontactno.setText("Contact No : ");
                           vollocation.setText("Location : ");
                           voldate.setText("Date : ");
                        }
                        
                        
                        
                        
                    }
                    
                }
                
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null," "+e);
                }
    }//GEN-LAST:event_volokActionPerformed

    private void volbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volbtnActionPerformed
        String gid=u_id.getText();
        int vvid=Integer.parseInt(gid);
        
        String vunit=voleunits.getText();
        String vtime=voletime.getText();
        
       
        
        if(vunit.length()==0 || vtime.length()==0)
        {
            errormsg.setText("Please fill out the fields");
        }
        
        else{
            
            try{
                
                if (bloodGroupChecker.contains(UserDetails.bloodGroup)) {
                    int vid2=Integer.parseInt(UserDetails.id);
                    String query="Insert into Volunteer (v_id,req_id,v_name,v_bloodgroup,v_time,v_units) VALUES(?,?,?,?,?,?)";
                
                    PreparedStatement prepare=conn.prepareStatement(query);
                    prepare.setInt(1, vid2);
                    prepare.setInt(2, vvid);
                    prepare.setString(3, " "+UserDetails.name);
                    prepare.setString(4, " "+UserDetails.bloodGroup);
                    prepare.setString(5, " "+vunit);
                    prepare.setString(6, " "+vtime);
                    prepare.executeUpdate();
               
                    errormsg.setForeground(Color.green);
                    errormsg.setText("You have volunteered for this requirement");
                    voleunits.setText("");
                    voletime.setText("");
                }
                
                else if (!bloodGroupChecker.contains(UserDetails.bloodGroup)) {
                    errormsg.setForeground(Color.red);
                    errormsg.setText("Your blood group doesn't match the required blood group");
                    JOptionPane.showMessageDialog(null, " "+UserDetails.bloodGroup);
                    JOptionPane.showMessageDialog(null, ""+bloodGroupChecker);
                    voleunits.setText("");
                    voletime.setText("");
                }
                
            }
            
            
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, " "+e);
            }
            
            
        }
    }//GEN-LAST:event_volbtnActionPerformed

    private void comentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comentbtnActionPerformed
        String comment=volcomment.getText();
        int a=Integer.parseInt(UserDetails.id);
        
        if (comment.length()==0) {
            errormsg.setForeground(Color.red);
            errormsg.setText("Please write a comment");
            JOptionPane.showMessageDialog(null,"Please write a comment");
        }
        
        else {
            String requestID = u_id.getText();
            int intr_id = Integer.parseInt(requestID);
            try{
                
                String query2="Insert into VolunteerComment (req_id,v_id,v_name,v_comment) VALUES(?,?,?,?)";
                PreparedStatement prepare=conn.prepareStatement(query2);
                prepare.setString(1, " "+intr_id);
                prepare.setString(2, " "+a);
                prepare.setString(3, " "+UserDetails.name);
                prepare.setString(4, " "+comment);
                prepare.executeUpdate();
                
                errormsg.setForeground(Color.green);
                errormsg.setText("Comment added Sucessfully");
                JOptionPane.showMessageDialog(null,"Comment added Sucessfully");
                volcomment.setText("");
                
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null," "+e);
            }
        }
        
        
    }//GEN-LAST:event_comentbtnActionPerformed

    private void u_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_u_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comentbtn;
    private javax.swing.JLabel errormsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField u_id;
    private javax.swing.JLabel volblood;
    private javax.swing.JButton volbtn;
    private javax.swing.JTextArea volcomment;
    private javax.swing.JLabel volcontactno;
    private javax.swing.JLabel voldate;
    private javax.swing.JTextField voletime;
    private javax.swing.JTextField voleunits;
    private javax.swing.JLabel vollocation;
    private javax.swing.JLabel volname;
    private javax.swing.JButton volok;
    private javax.swing.JLabel volurgency;
    // End of variables declaration//GEN-END:variables
}
