/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbanksystem;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author ABC
 */
public class volunteerlistmodel extends javax.swing.JPanel implements ListCellRenderer<volunteerObject> {

    /**
     * Creates new form volunteerlistmodel
     */
    public volunteerlistmodel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vname = new javax.swing.JLabel();
        vbg = new javax.swing.JLabel();
        vcno = new javax.swing.JLabel();
        vtime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        vname.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        vname.setText("Name : ");

        vbg.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        vbg.setText("Blood Group : ");

        vcno.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        vcno.setText("Units : ");

        vtime.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        vtime.setText("Time : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vname)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vbg)
                        .addGap(51, 51, 51)
                        .addComponent(vtime))
                    .addComponent(vcno))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vbg)
                    .addComponent(vtime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vcno)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel vbg;
    private javax.swing.JLabel vcno;
    private javax.swing.JLabel vname;
    private javax.swing.JLabel vtime;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends volunteerObject> list, volunteerObject value, int index, boolean isSelected, boolean cellHasFocus) {
        this.vname.setText(value.name);
        this.vbg.setText(value.bloodGroup);
        this.vcno.setText(value.contactNo);
        this.vtime.setText(value.time);
       return this;
    }
}
